---
title: "Homework_03"
author: "Kelsey Soule"
date: "2024-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1.

```
STRING:
First String    Second      1.22      3.4
Second          More Text   1.555555  2.2220
Third           x           3         124

FIND:\s{2,}  
REPLACE:,

RESULT:
First String,Second,1.22,3.4
Second,More Text,1.555555,2.2220
Third,x,3,124
```
The above regular expression worked to grab 2 or more spaces. I set it to be 2 or more so that it wouldn't pick up the single space between the phrase 'First String'. Then I could replace the spaces with a comma.

### 2.

```
STRING:
Ballif, Bryan, University of Vermont
Ellison, Aaron, Harvard Forest
Record, Sydne, Bryn Mawr

FIND:(\w+),\s*(\w+), (.*)  
REPLACE:\2 \1 (\3)

RESULT:
Bryan Ballif (University of Vermont)
Aaron Ellison (Harvard Forest)
Sydne Record (Bryn Mawr)
```
The first piece of the regular expression grabs the first word, and saves it so it can be referred to in REPLACE. Then I account for the comma and space that I don't want to keep. Then I grabbed the next word in the string, and put it in parentheses so I could refer to it in REPLACE. I accounted for the other comma and space I don't want to keep, and grabbed all the rest, which was the University name. 

### 3.

```
STRING:
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 0003 Winder Slide.mp3 0004 Walking Cane.mp3

FIND:\d+ (\w+ \w+\s*\w*\s*\w*\.\w+ )
REPLACE:\1 \2\n

RESULT:
0001 Georgia Horseshoe.mp3 
0002 Billy In The Lowground.mp3 
0003 Winder Slide.mp3 
0004 Walking Cane.mp3
```
This regular expression includes the first number string, then grabs the song name and mps extension. I set it to require at least two words, because that was the minimum amount of words in a song title for the given list. The other words used an asterisk which mean zero or more, so they could or couldn't be there. I went up to 4 possible words. 

### 4.

```
STRING:
0001 Georgia Horseshoe.mp3 
0002 Billy In The Lowground.mp3 
0003 Winder Slide.mp3 
0004 Walking Cane.mp3

FIND:(\d+) (\w+ \w+\s*\w*\s*\w*)(\.\w+)
REPLACE:\2_\1\3

RESULT:
Georgia Horseshoe_0001.mp3 
Billy In The Lowground_0002.mp3 
Winder Slide_0003.mp3 
Walking Cane_0004.mp3
```
This regular expression grabs the number string, then grabs the song title *before* the mp3 extension, and separately grabs the mps extension. This way I could reorder the pieces in the desired way.

### 5.

```
STRING:
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55

FIND:(\w)\w*,(\w*,)\d*.\d*,(\d*)
REPLACE:\1_\2\3

RESULT:
C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55
```
This regular expression grabs the first letter of the first word, then includes the rest of the word. Then it grabs the entire second word, and only the last number. It only grabs these things with parentheses because that was all we needed for the desired result. You have to include the parts you don't want to grab so that you can still highlight the whole line.

### 6. 

```
STRING:
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55

FIND:(\w)\w*,(\w{4})\w*.\d*.\d*(,\d*)
REPLACE:\1_\2\3

RESULT:
C_penn,44
C_herc,3
M_punc,4
L_neon,55
```
This regular expression grabs the first letter of the first word, then includes the rest of the word. Then it grabs the first four letters of the second word. Again, only the last number is grabbed.

### 7.

```
STRING:
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55

FIND:(\w{3})\w*,(\w{3})\w*,(\d*.\d*),(\d*)
REPLACE:\1\2, \4, \3

RESULT:
Campen, 44, 10.2
Camher, 3, 10.5
Myrpun, 4, 12.2
Lasneo, 55, 3.3
```
This regular expression grabs the first three letters of each word. It grabs the two numbers separately so that they can be reordered in REPLACE.